### ISSUE TITLE
No module named 'rmt_utils'

### ISSUE THREAD

**Issue by zanjani99** [OswaldHe/HMT-pytorch#6]
I am reaching out to inquire about a potential issue I encountered while working with the repository. I am attempting to import modeling_rmt . However, I am receiving an error indicating that the rmt_utils module cannot be found.

Error Message:

> ModuleNotFoundError: No module named 'rmt_utils'

This error occurs in the line:

`
from rmt_utils.encoder import horizontal_memory_forward
`

This line suggests that the code expects a module named rmt_utils to be present within the repository

**I would be grateful if you could clarify the intended structure of the repository regarding the rmt_utils module. Is this module expected to be present in the current codebase?**
Thank you for your time and assistance.

**Comment by OswaldHe** [comment]
Hi,

Thank you for your interest in HMT! I just removed all legacy files from the RMT repository that is not used in HMT. It should work now. Let me know if there is any further question.

Zifan
